# Generated by Django 4.2 on 2023-06-02 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='customer',
            name='contact',
            field=models.EmailField(max_length=254),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
